# Fun

Fun in life is essential. It gives you a purpose, aside from just working hard.

## Überzeugen

Eines der mächtigsten Waffen, die es gibt, ist - anhand deines Wissens - Leute von deinen Ideen zu überzeugen. Hier habe ich einige Beispiele aufgelistet, mit denen du überzeugen kannst.

- Using Scientific Evidence - aka Data, e.g. objective truths - VS. Knowledge on the Internet - aka subjective Bias & Confirmation: [Scientific Thinking and Communication](https://www.youtube.com/watch?v=io6QdGcoWMU&t=1m15s)

## Crypto

Since the publication of a White-Paper in 2008 form a guy named Satoshi, the **blockchain-technology** and one of its first innovations - **Crypto-Currencies** - have become immensly hyped up across the glob. 

As of today, the 14.12.2021, Bitcoin is worth around 60'000 CHF and the enthousiasm about it is not slowing down, even when enormous sceptisism still remains. 

> But what is the essence behind Crypto-Currencies and the Blockchain-Technology?

- I found a very interesting video today that tries to go to the core of it: [Explanation of the Blockchain-Technology to the American Congress](https://www.youtube.com/watch?v=pSTNhBlfV_s&t=1m30s)

